name: MySQL for GitHub Actions

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
       runs-on: windows-latest
       steps:
        - uses: actions/checkout@v1
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDS }}
        
        - uses: azure/mysql@v1
          with:
              server-name: mysql-okcu-cloud.mysql.database.azure.com 
              connection-string: ${{ secrets.AZURE_MYSQL_PASSWORD }}
              sql-file: './data.sql'
